name: Extract boot.7z to Root (Keep Original)

on:
  push:
    paths:
      - 'boot.7z' # 当 boot.7z 文件被推送到仓库时触发此工作流
  workflow_dispatch:
    # 允许你手动从 GitHub Actions 页面运行此工作流，方便测试

jobs:
  extract_and_commit:
    runs-on: ubuntu-latest # 或者 'windows-latest' 如果你需要特定的 Windows 环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 这确保了 Git Action 有权限推送更改
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install 7-Zip
        run: |
          sudo apt-get update
          sudo apt-get install p7zip-full -y

      - name: Extract boot.7z to root directory # 解压到根目录
        run: |
          # 7z x boot.7z -o./ 表示解压到当前目录 (即仓库根目录)
          7z x boot.7z -o./
          # 如果 boot.7z 有密码，可以使用 -p 选项：
          # 7z x boot.7z -o./ -pYOUR_PASSWORD_HERE

      - name: Configure Git for Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add and Commit extracted files
        run: |
          # 添加所有新文件或修改的文件，但不包括 boot.7z 的删除操作
          git add .
          # 仅在有实际更改时才提交
          git diff-index --quiet HEAD || git commit -m "Automated: Extract boot.7z to root"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GITHUB_TOKEN 进行认证
